### ISSUE TITLE
Implement Space

### ISSUE THREAD

**Issue by h0n9** [postie-labs/go-postie-client#7]

**Comment by h0n9** [comment]
```yaml
spaces:
  space-A:
    stories:
      hello-world:
        capsules:
          - timestamp: 123456789
            msg: blahblah
```
